const PRIMARYCOLOR = '#f9f9f9'; // whiteish
const SECONDARYCOLOR = '#37c871'; // greenish
const TEXTCOLOR = '#333333'; // grayish
const SUBHEADINGCOLOR = '#b7c8be';
const CONTRASTCOLOR = '#FF3F48'; // red

export { PRIMARYCOLOR, SECONDARYCOLOR, TEXTCOLOR, SUBHEADINGCOLOR, CONTRASTCOLOR };
